#!/usr/bin/env python3
"""One-shot production setup on free tiers ($0, no card).

    backend/pfeenv/bin/python deploy/setup_free.py           # do everything
    backend/pfeenv/bin/python deploy/setup_free.py --check   # only validate inputs

Reads deploy/.env.deploy (git-ignored) and, step by step:
  1. database  - connects to Neon and creates/updates the tables
  2. email     - sends a test email through Gmail SMTP to the Gmail address
  3. render    - sets DATABASE_URL, SMTP_*, JOBS_TOKEN on the API service and
                 redeploys the API and the website (new frontend build)
  4. verify    - checks the live API now keeps history
  5. schedule  - creates the cron-job.org job that calls POST /jobs/nightly
                 every 10 minutes between 02:00 and 03:50 UTC
  6. trigger   - runs the nightly job once, now

Every step is idempotent: re-running it after fixing a value is safe.
Secrets are never printed.
"""
import argparse
import os
import secrets
import sys
import time

import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND = os.path.join(ROOT, "backend")
ENV_FILE = os.path.join(ROOT, "deploy", ".env.deploy")
sys.path.insert(0, BACKEND)

RENDER = "https://api.render.com/v1"
CRONJOB = "https://api.cron-job.org"
API_NAME, WEB_NAME = "github-analyzer-api", "github-analyzer-web"
CRON_TITLE = "Git Analyzer nightly"
REQUIRED = ["NEON_DATABASE_URL", "GMAIL_ADDRESS", "GMAIL_APP_PASSWORD", "RENDER_API_KEY", "CRONJOB_API_KEY"]


def ok(msg):
    print(f"  ✓ {msg}")


def fail(msg):
    print(f"  ✗ {msg}")
    sys.exit(1)


def load_env():
    values = {}
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                values[k.strip()] = v.strip().strip('"').strip("'")
    values["GMAIL_APP_PASSWORD"] = values.get("GMAIL_APP_PASSWORD", "").replace(" ", "")
    return values


def save_value(key, value):
    with open(ENV_FILE) as f:
        lines = f.read().splitlines()
    lines = [l for l in lines if not l.startswith(f"{key}=")]
    lines += ["", "# generated by setup_free.py (shared secret for the nightly trigger)", f"{key}={value}"]
    with open(ENV_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


def check(env):
    missing = [k for k in REQUIRED if not env.get(k)]
    if missing:
        fail("still empty in deploy/.env.deploy: " + ", ".join(missing))
    if not env["NEON_DATABASE_URL"].startswith(("postgresql://", "postgres://")):
        fail("NEON_DATABASE_URL must start with postgresql://")
    if "@" not in env["GMAIL_ADDRESS"]:
        fail("GMAIL_ADDRESS does not look like an email address")
    if len(env["GMAIL_APP_PASSWORD"]) != 16:
        fail("GMAIL_APP_PASSWORD should be the 16-letter app password, not the account password")
    ok("all values present")


def step_database(env):
    print("1. database")
    import db
    db.configure(env["NEON_DATABASE_URL"])
    db.upgrade()
    from sqlalchemy import inspect
    tables = set(inspect(db.engine()).get_table_names())
    need = {"repositories", "analysis_runs", "watches", "alerts"}
    if not need <= tables:
        fail(f"tables missing after migration: {sorted(need - tables)}")
    ok("connected to Neon, tables are up to date")


def smtp_env(env):
    return {
        "SMTP_HOST": "smtp.gmail.com", "SMTP_PORT": "587",
        "SMTP_USERNAME": env["GMAIL_ADDRESS"], "SMTP_PASSWORD": env["GMAIL_APP_PASSWORD"],
        "SMTP_FROM": f"Git Analyzer <{env['GMAIL_ADDRESS']}>",
    }


def step_email(env):
    print("2. email")
    os.environ.update(smtp_env(env))
    from services import notify
    if not notify.send_email(env["GMAIL_ADDRESS"], "Git Analyzer: email works",
                             "This test email confirms that Git Analyzer can send alerts from this address."):
        fail("Gmail refused the login. Check 2-Step Verification is on and the app password is right.")
    ok(f"test email sent to {env['GMAIL_ADDRESS']}")


def render(env, method, path, **kw):
    r = requests.request(method, RENDER + path, timeout=30,
                         headers={"Authorization": f"Bearer {env['RENDER_API_KEY']}", "Accept": "application/json"}, **kw)
    if r.status_code >= 400:
        fail(f"Render API {method} {path}: {r.status_code} {r.text[:200]}")
    return r.json() if r.text else None


def find_services(env):
    found = {}
    for item in render(env, "GET", "/services", params={"limit": 100}):
        svc = item.get("service", item)
        if svc.get("name") in (API_NAME, WEB_NAME):
            found[svc["name"]] = svc
    for name in (API_NAME, WEB_NAME):
        if name not in found:
            fail(f"no Render service named {name} in this account")
    return found[API_NAME], found[WEB_NAME]


def wait_live(env, svc, deploy_id, label):
    t0 = time.time()
    while time.time() - t0 < 25 * 60:
        d = render(env, "GET", f"/services/{svc['id']}/deploys/{deploy_id}")
        status = d.get("status")
        if status == "live":
            ok(f"{label} deployed in {int(time.time() - t0)} s")
            return
        if status in ("build_failed", "update_failed", "canceled", "deactivated", "pre_deploy_failed"):
            fail(f"{label} deploy ended with status {status}: see the Render dashboard logs")
        time.sleep(15)
    fail(f"{label} deploy did not finish in 25 minutes")


def step_render(env):
    print("3. render")
    api, web = find_services(env)
    ok(f"found {API_NAME} and {WEB_NAME}")
    if not env.get("JOBS_TOKEN"):
        env["JOBS_TOKEN"] = secrets.token_urlsafe(32)
        save_value("JOBS_TOKEN", env["JOBS_TOKEN"])
    values = {"DATABASE_URL": env["NEON_DATABASE_URL"], "JOBS_TOKEN": env["JOBS_TOKEN"], **smtp_env(env)}
    for key, value in values.items():
        render(env, "PUT", f"/services/{api['id']}/env-vars/{key}", json={"value": value})
    ok("API settings saved: " + ", ".join(values))
    api_deploy = render(env, "POST", f"/services/{api['id']}/deploys", json={"clearCache": "do_not_clear"})
    web_deploy = render(env, "POST", f"/services/{web['id']}/deploys", json={"clearCache": "clear"})
    print("  ... deploying (a few minutes on the free tier)")
    wait_live(env, api, api_deploy["id"], "API")
    wait_live(env, web, web_deploy["id"], "website")
    return api["serviceDetails"]["url"].rstrip("/"), web["serviceDetails"]["url"].rstrip("/")


def step_verify(api_url):
    print("4. verify")
    r = requests.get(f"{api_url}/history", params={"repo_url": "https://github.com/pallets/flask"}, timeout=120)
    if r.status_code != 200 or r.json().get("enabled") is not True:
        fail(f"the live API does not keep history yet: {r.status_code} {r.text[:200]}")
    ok("live API is connected to the database")


def step_schedule(env, api_url):
    print("5. schedule")
    headers = {"Authorization": f"Bearer {env['CRONJOB_API_KEY']}", "Content-Type": "application/json"}
    job = {
        "url": f"{api_url}/jobs/nightly", "enabled": True, "title": CRON_TITLE,
        "saveResponses": True, "requestMethod": 1, "requestTimeout": 30,
        "extendedData": {"headers": {"Authorization": f"Bearer {env['JOBS_TOKEN']}"}, "body": ""},
        "schedule": {"timezone": "UTC", "expiresAt": 0, "hours": [2, 3],
                     "minutes": [0, 10, 20, 30, 40, 50], "mdays": [-1], "months": [-1], "wdays": [-1]},
    }
    r = requests.get(f"{CRONJOB}/jobs", headers=headers, timeout=30)
    if r.status_code != 200:
        fail(f"cron-job.org API: {r.status_code} {r.text[:200]}")
    existing = [j for j in r.json().get("jobs", []) if j.get("title") == CRON_TITLE]
    if existing:
        jid = existing[0]["jobId"]
        r = requests.patch(f"{CRONJOB}/jobs/{jid}", headers=headers, json={"job": job}, timeout=30)
    else:
        r = requests.put(f"{CRONJOB}/jobs", headers=headers, json={"job": job}, timeout=30)
    if r.status_code >= 400:
        fail(f"cron-job.org could not save the job: {r.status_code} {r.text[:200]}")
    ok("nightly trigger scheduled: every 10 min, 02:00-03:50 UTC")


def step_trigger(env, api_url):
    print("6. trigger once")
    r = requests.post(f"{api_url}/jobs/nightly", headers={"Authorization": f"Bearer {env['JOBS_TOKEN']}"}, timeout=60)
    if r.status_code not in (200, 202):
        fail(f"trigger refused: {r.status_code} {r.text[:200]}")
    ok(f"nightly job answered: {r.json().get('status')}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true", help="only validate deploy/.env.deploy")
    args = p.parse_args()
    env = load_env()
    print("0. inputs")
    check(env)
    if args.check:
        return
    step_database(env)
    step_email(env)
    api_url, web_url = step_render(env)
    step_verify(api_url)
    step_schedule(env, api_url)
    step_trigger(env, api_url)
    print(f"\nAll set. Website: {web_url}\nAPI: {api_url}")


if __name__ == "__main__":
    main()
